public enum TypeTravail {
    ROUTIER,
    GAZ_ELECTRIQUE,
    CONSTRUCTION_RENOVATION,
    ENTRETIEN_PAYSAGE,
    TRANSPORT_COMMUN,
    SIGNALISATION_ECHANGE,
    SOUTERRAIN,
    RESIDENTIEL,
    URBAIN,
    RESEAUX_TELECOM
}
